Handphone = ['Xiaomi', 'Realme', 'Xiaomi', 'Huawei' ]
print('----copy----')
print(Handphone)
HP_Cina = Handphone.copy()
print(HP_Cina)
print('----clear----')
Handphone.clear()
print(Handphone)
print('----append----')
Handphone.append('Samsung')
print(Handphone)
print('----pop----')
HP_Cina.pop()
print(HP_Cina)
print('----extend----')
Handphone.extend(HP_Cina)
print(Handphone)
print('----count----')
mi = Handphone.count("Xiaomi")
print(mi)
print('----index----')
ei = Handphone.index("Samsung")
print(ei)
print('----insert----')
Handphone.insert(1, "iPhone")
print(Handphone)
print('----remove----')
Handphone.remove("Xiaomi")
print(Handphone)
print('----reverse----')
Handphone.reverse()
print(Handphone)
print('----sort----')
Handphone.sort()
print(Handphone)